[2024-11-05T19:05:57.121+0700] {processor.py:186} INFO - Started process (PID=66960) to work on /home/3323600030_Aulia/airflow/dags/case_study.py
[2024-11-05T19:05:57.132+0700] {processor.py:914} INFO - Processing file /home/3323600030_Aulia/airflow/dags/case_study.py for tasks to queue
[2024-11-05T19:05:57.153+0700] {logging_mixin.py:190} INFO - [2024-11-05T19:05:57.149+0700] {dagbag.py:588} INFO - Filling up the DagBag from /home/3323600030_Aulia/airflow/dags/case_study.py
[2024-11-05T19:05:57.191+0700] {logging_mixin.py:190} INFO - [2024-11-05T19:05:57.180+0700] {dagbag.py:387} ERROR - Failed to import: /home/3323600030_Aulia/airflow/dags/case_study.py
Traceback (most recent call last):
  File "/home/3323600030_Aulia/venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/3323600030_Aulia/airflow/dags/case_study.py", line 5, in <module>
    from resources.scripts.case_study import extract_logic, load_logic, update_ingest_type_logic
  File "/home/3323600030_Aulia/airflow/dags/resources/scripts/case_study/__init__.py", line 1, in <module>
    from resources.scripts.case_study.extract import extract_logic
  File "/home/3323600030_Aulia/airflow/dags/resources/scripts/case_study/extract.py", line 4, in <module>
    from airflow.providers.mysql.hooks.mysql import MySqlHook
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2024-11-05T19:05:57.202+0700] {processor.py:927} WARNING - No viable dags retrieved from /home/3323600030_Aulia/airflow/dags/case_study.py
[2024-11-05T19:05:57.385+0700] {processor.py:208} INFO - Processing /home/3323600030_Aulia/airflow/dags/case_study.py took 0.308 seconds
